# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - feature/*
  - fix/*
  - release/*

pool:
  vmImage: ubuntu-latest

steps:

  - task: UseDotNet@2
    displayName: Install .NET Core 3.1
    timeoutInMinutes: 5
    inputs:
      packageType: 'sdk'
      version: '3.1.x'

  - task: UseDotNet@2
    displayName: Install .NET 5
    timeoutInMinutes: 5
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    displayName: Restore all projects
    timeoutInMinutes: 10
    inputs:
      command: 'restore'
      projects: '$(Build.SourceDirectory)/src/**/*.csproj'
      feedsToUse: 'config'
      nugetConfigPath: '$(Build.SourceDirectory)/src/nuget.org'
      configuration: Debug

  - task: DotNetCoreCLI@2
    displayName: Build all projects
    timeoutInMinutes: 15
    inputs:
      command: 'build'
      projects: '$(Build.SourceDirectory)/src/**/*.csproj'
      configuration: Debug