# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - feature/*
  - fix/*
  - release/*

pr:
 branches:
   exclude:
     - master
     - feature/*
     - fix/*
     - release/*

variables:

  - template: templates/variables.yml

pool:
  vmImage: ubuntu-latest

steps:

  - template: templates/steps/sdk-install.yml

  - template: templates/steps/restore&build.yml